#Server
server:
  port: 80
#Spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/poidb?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
